version: '3.5'
services:
  db:
    container_name: contact-importer-api-db
    image: postgres:10.5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports: ["5432:5432"]
    expose: ["5432"]

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  # sidekiq:
  #   depends_on:
  #     - 'db'
  #     - 'redis'
  #   build: .
  #   command: bundle exec sidekiq
  #   volumes:
  #     - .:/app
  #   environment:
  #     - REDIS_URL_SIDEKIQ=redis://redis:6379/1

  web:
    build:
      context: .
    container_name: contact-importer-api-web
    command: bash -c "while [ true ]; do sleep 10; done"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

volumes:
  redis: